config/routes.rb
Flixter::Application.routes.draw do
  devise_for :users
  resource :dashboard, only: [:show]
  root 'static_pages#index' 
  get 'privacy', to: 'static_pages#privacy'
  # GET/lessons/new
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  resources :lessons, only: [:show]
  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
    end
  end
  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/course.rb
class Course < ActiveRecord::Base
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :sections
    has_many :enrollments

    validates :title, presence: true
    validates :description, presence: true
    validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}
    def free?
        cost.zero?
    end

    def premium?
    ! free?
  end
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :course
  belongs_to :user
end

app/models/image.rb
class Image < ActiveRecord::Base
    belongs_to :section
    mount_uploader :image, ImageUploader
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
    belongs_to :section
    mount_uploader :video, VideoUploader

    include RankedModel
    ranks :row_order, :with_same => :section_id

  def next_lesson
    lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
    if lesson.blank? && section.next_section
      return section.next_section.lessons.rank(:row_order).first
    end
    return lesson
  end
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :course
  has_many :lessons
  has_many :images
  include RankedModel
  ranks :row_order, :with_same => :course_id

  def next_section
    section = course.sections.where("row_order > ?", self.row_order).rank(:row_order).first

    return section
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :courses
  has_many :enrollments
  has_many :enrolled_courses, through: :enrollments, source: :course
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def enrolled_in?(course)
    return enrolled_courses.include?(course)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
    before_action :authenticate_user!
    def show
    end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!

  def create
    if current_course.premium?
    current_user.enrollments.create(course: current_course)
    

    # Amount in cents
    @amount = (current_course.cost * 100).to_i

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Flixter Premo Content',
      :currency    => 'usd'
    )
  end
  current_user.enrollments.create(course: current_course)
  redirect_to course_path(current_course)
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path
  end

  private

  def current_course
    @current_course ||= Course.find(params[:course_id])
  end
end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
    before_action :authenticate_user!
    before_action :require_authorized_for_current_course, only: [:show]
    def new
        @course = Course.new
    end

    def create
        @course = current_user.courses.create(course_params)
        if @course.valid?
         redirect_to instructor_course_path(@course)
        else
         render :new, status: :unprocessable_entity
    end
    end

    def show
      @section = Section.new
      @lesson = Lesson.new
    end
    
    private
    def require_authorized_for_current_course
     if current_course.user != current_user
      render text: "Unauthorized", status: :unauthorized
     end
    end

    helper_method :current_course
    def current_course
      @current_course ||= Course.find(params[:id])
    end


    def course_params
      params.require(:course).permit(:title, :description, :cost, :image)
    end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

    def show
    end

    private
    helper_method :current_lesson
    def current_lesson
        @current_lesson ||= Lesson.find(params[:id])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def index
    end

    def privacy
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/courses/index.html.erb
<br />

<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1 class="text-center">Learn something today</h1>
  <hr />

  <% @courses.each do |course| %>
    <h2 class="text-center">
      <%= link_to course.title, course_path(course) %>
    </h2>
    <br />
    <div class="col-sm-8 col-xs-12">
      <%= course.description %>
    </div>
    <div class="col-sm-4 col-xs-12 text-center">
      <%= link_to 'Interested?', course_path(course), class: 'btn btn-primary btn-large' %>
    </div>
    <br class="clr" />
  <% end %>
</div>

app/views/courses/show.html.erb
<br />

<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1> <%=@course.title%> </h1>
  <%= image_tag @course.image, class: 'img-responsive' %>
  <br />
  <div class="col-sm-4 col-xs-12 text-center">
   <span class="label label-default">
    <%= number_to_currency @course.cost %>
    </span>

    <% if current_user && current_user == @course.user %>
      <br />
      <br />
      <%= link_to 'Administer', instructor_course_path(@course), class: 'btn btn-danger btn-large' %>
    <% end %>

    <br />
    <br />
    <% if current_user && current_user.enrolled_in?(@course) %>
      <h3 class="label label-info">You Are Enrolled!</h3>
    <% else %>

    <% if @course.free? %>
      <%= link_to 'Enroll', course_enrollments_path(@course), class: 'btn btn-primary', method: :post %>
    <% else %>
      <%= form_tag course_enrollments_path(@course) do %>
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description="<%= @course.title %> (<%= number_to_currency @course.cost %>)"
                data-amount="<%= (@course.cost * 100).to_i %>"></script>
      <% end %>


 <% end %>

    <% end %>

  </div>

  <div class="col-sm-8 col-xs-12">
    <%= @course.description %>
  </div>

  <div class="col-xs-12">
    <% @course.sections.each do |section| %>
      <div class="section">
      <h3>
          <%= section.title %>
        </h3>
        <% section.lessons.rank(:row_order).each do |lesson| %>
        <div class="col-xs-12 col-sm-6">
        <div class="lesson text-center">
        <%= link_to lesson_path(lesson) do %>
              <b><%= lesson.title %></b>
              <br />
              <%= lesson.subtitle %>
            <% end %>
          </div>
          </div>
        <% end %>
        
        <br class="clr" />
      </div>
    <% end %>
  </div>

</div>